### ISSUE TITLE
I can't figure out how to fix the required properties.

### ISSUE THREAD

**Issue by maddycpierce** [maddycpierce/horizontal-nav#1]
Markbot is telling me:
"Expected to see margin with a different value inside body {}" and "Expected to see font-family with a different value inside h1 {}". How can I fix this please?

**Comment by maddycpierce** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
_Re: font-family_

Change the backup font for `Bevan` to `serif`—`cursive` is a really bad choice on Google’s part for a backup font.

---

_Re: body margin_

Its `margin` should be exactly `0`, that's all, like this:

``` css
margin: 0;
```

**Comment by maddycpierce** [comment]
thank you!
